/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_MetadataSet */

#ifndef _Included_com_intel_vmf_MetadataSet
#define _Included_com_intel_vmf_MetadataSet
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_vmf_MetadataSet_FRAME_COUNT_ALL
#define com_intel_vmf_MetadataSet_FRAME_COUNT_ALL 9223372036854775807i64
/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_MetadataSet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1MetadataSet__
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_MetadataSet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataSet_n_1MetadataSet__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_setTo
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataSet_n_1setTo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryByFrameIndex
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryByFrameIndex
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryByTime
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryByTime
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryBySchema
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryBySchema
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryByName
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryByName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryByNameAndValue
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryByNameAndValue
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryByNameAndFields
 * Signature: (JLjava/lang/String;[J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryByNameAndFields
  (JNIEnv *, jclass, jlong, jstring, jlongArray);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryByReference
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryByReference__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryByReference
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryByReference__JLjava_lang_String_2J
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_queryByReference
 * Signature: (JLjava/lang/String;[J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1queryByReference__JLjava_lang_String_2_3J
  (JNIEnv *, jclass, jlong, jstring, jlongArray);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_shift
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSet_n_1shift
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataSet
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataSet_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
