/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_MetadataSchema */

#ifndef _Included_com_intel_vmf_MetadataSchema
#define _Included_com_intel_vmf_MetadataSchema
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_vmf_MetadataSchema_STD_DST
#define com_intel_vmf_MetadataSchema_STD_DST 0L
/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_MetadataSchema
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSchema_n_1MetadataSchema
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_MetadataSchema_n_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_getAuthor
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_MetadataSchema_n_1getAuthor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSchema_n_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_add
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataSchema_n_1add
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_findMetadataDesc
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSchema_n_1findMetadataDesc
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_getAll
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_vmf_MetadataSchema_n_1getAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_getStdSchemaName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_MetadataSchema_n_1getStdSchemaName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_getStdSchema
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataSchema_n_1getStdSchema
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_vmf_MetadataSchema
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataSchema_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
