/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_Vmf */

#ifndef _Included_com_intel_vmf_Vmf
#define _Included_com_intel_vmf_Vmf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vmf_Vmf
 * Method:    n_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Vmf_n_1initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_vmf_Vmf
 * Method:    n_terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Vmf_n_1terminate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
