/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_MetadataDesc */

#ifndef _Included_com_intel_vmf_MetadataDesc
#define _Included_com_intel_vmf_MetadataDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_MetadataDesc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataDesc_n_1MetadataDesc__
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_MetadataDesc
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataDesc_n_1MetadataDesc__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_MetadataDesc
 * Signature: (Ljava/lang/String;[J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataDesc_n_1MetadataDesc__Ljava_lang_String_2_3J
  (JNIEnv *, jobject, jstring, jlongArray);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_MetadataDesc
 * Signature: (Ljava/lang/String;[J[J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataDesc_n_1MetadataDesc__Ljava_lang_String_2_3J_3J
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_getMetadataName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_MetadataDesc_n_1getMetadataName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_getSchemaName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_MetadataDesc_n_1getSchemaName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_getFields
 * Signature: (J)[Lcom/intel/vmf/FieldDesc;
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_vmf_MetadataDesc_n_1getFields
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_getAllReferenceDescs
 * Signature: (J)[Lcom/intel/vmf/ReferenceDesc;
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_vmf_MetadataDesc_n_1getAllReferenceDescs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_declareCustomReference
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataDesc_n_1declareCustomReference
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_getReferenceDesc
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataDesc_n_1getReferenceDesc
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_getFieldDesc
 * Signature: (JLcom/intel/vmf/FieldDesc;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_MetadataDesc_n_1getFieldDesc
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     com_intel_vmf_MetadataDesc
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataDesc_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
