/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_FieldValue */

#ifndef _Included_com_intel_vmf_FieldValue
#define _Included_com_intel_vmf_FieldValue
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_vmf_FieldValue_type_unknown
#define com_intel_vmf_FieldValue_type_unknown 0L
#undef com_intel_vmf_FieldValue_type_char
#define com_intel_vmf_FieldValue_type_char 1L
#undef com_intel_vmf_FieldValue_type_integer
#define com_intel_vmf_FieldValue_type_integer 2L
#undef com_intel_vmf_FieldValue_type_real
#define com_intel_vmf_FieldValue_type_real 3L
#undef com_intel_vmf_FieldValue_type_string
#define com_intel_vmf_FieldValue_type_string 4L
#undef com_intel_vmf_FieldValue_type_vec2d
#define com_intel_vmf_FieldValue_type_vec2d 5L
#undef com_intel_vmf_FieldValue_type_vec3d
#define com_intel_vmf_FieldValue_type_vec3d 6L
#undef com_intel_vmf_FieldValue_type_vec4d
#define com_intel_vmf_FieldValue_type_vec4d 7L
#undef com_intel_vmf_FieldValue_type_rawbuffer
#define com_intel_vmf_FieldValue_type_rawbuffer 8L
#undef com_intel_vmf_FieldValue_type_char_vector
#define com_intel_vmf_FieldValue_type_char_vector 9L
#undef com_intel_vmf_FieldValue_type_integer_vector
#define com_intel_vmf_FieldValue_type_integer_vector 10L
#undef com_intel_vmf_FieldValue_type_real_vector
#define com_intel_vmf_FieldValue_type_real_vector 11L
#undef com_intel_vmf_FieldValue_type_string_vector
#define com_intel_vmf_FieldValue_type_string_vector 12L
#undef com_intel_vmf_FieldValue_type_vec2d_vector
#define com_intel_vmf_FieldValue_type_vec2d_vector 13L
#undef com_intel_vmf_FieldValue_type_vec3d_vector
#define com_intel_vmf_FieldValue_type_vec3d_vector 14L
#undef com_intel_vmf_FieldValue_type_vec4d_vector
#define com_intel_vmf_FieldValue_type_vec4d_vector 15L
/*
 * Class:     com_intel_vmf_FieldValue
 * Method:    n_FieldValue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_FieldValue_n_1FieldValue__
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_vmf_FieldValue
 * Method:    n_FieldValue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_FieldValue_n_1FieldValue__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_FieldValue
 * Method:    n_FieldValue
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_FieldValue_n_1FieldValue__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_intel_vmf_FieldValue
 * Method:    n_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_FieldValue_n_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_FieldValue
 * Method:    n_isEqual
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_FieldValue_n_1isEqual
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_FieldValue
 * Method:    n_equals
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_FieldValue_n_1equals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_FieldValue
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_FieldValue_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
