/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_VmfInit */

#ifndef _Included_com_intel_vmf_VmfInit
#define _Included_com_intel_vmf_VmfInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vmf_VmfInit
 * Method:    n_vmfInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_VmfInit_n_1vmfInitialize
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_vmf_VmfInit
 * Method:    n_vmfTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_VmfInit_n_1vmfTerminate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
