/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_MetadataStream_VideoSegment */

#ifndef _Included_com_intel_vmf_MetadataStream_VideoSegment
#define _Included_com_intel_vmf_MetadataStream_VideoSegment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_VideoSegment
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1VideoSegment__
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_VideoSegment
 * Signature: (Ljava/lang/String;DJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1VideoSegment__Ljava_lang_String_2DJJJJ
  (JNIEnv *, jobject, jstring, jdouble, jlong, jlong, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_getTitle
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1getTitle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_setTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1setTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_getFPS
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1getFPS
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_setFPS
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1setFPS
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_getDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1getDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_setDuration
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1setDuration
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_getTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1getTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_setTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1setTime
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_getResolution
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1getResolution
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_setResolution
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1setResolution
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_intel_vmf_MetadataStream_VideoSegment
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataStream_00024VideoSegment_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
