/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_MetadataInternal */

#ifndef _Included_com_intel_vmf_MetadataInternal
#define _Included_com_intel_vmf_MetadataInternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vmf_MetadataInternal
 * Method:    n_MetadataInternal
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataInternal_n_1MetadataInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataInternal
 * Method:    n_MetadataInternalCopy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataInternal_n_1MetadataInternalCopy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataInternal
 * Method:    n_MetadataInternalByMD
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_MetadataInternal_n_1MetadataInternalByMD
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_MetadataInternal
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_MetadataInternal_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
