/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_Log */

#ifndef _Included_com_intel_vmf_Log
#define _Included_com_intel_vmf_Log
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_vmf_Log_LOG_INFO
#define com_intel_vmf_Log_LOG_INFO 0L
#undef com_intel_vmf_Log_LOG_WARNING
#define com_intel_vmf_Log_LOG_WARNING 1L
#undef com_intel_vmf_Log_LOG_ERROR
#define com_intel_vmf_Log_LOG_ERROR 2L
#undef com_intel_vmf_Log_LOG_NO_MESSAGE
#define com_intel_vmf_Log_LOG_NO_MESSAGE 3L
/*
 * Class:     com_intel_vmf_Log
 * Method:    n_logToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Log_n_1logToFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_intel_vmf_Log
 * Method:    n_logToConsole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Log_n_1logToConsole
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_vmf_Log
 * Method:    n_setVerbosityLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Log_n_1setVerbosityLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_vmf_Log
 * Method:    n_getVerbosityLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_vmf_Log_n_1getVerbosityLevel
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
