/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_XMLReader */

#ifndef _Included_com_intel_vmf_XMLReader
#define _Included_com_intel_vmf_XMLReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vmf_XMLReader
 * Method:    n_XMLReader
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_XMLReader_n_1XMLReader
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_vmf_XMLReader
 * Method:    n_parseSchemas
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_vmf_XMLReader_n_1parseSchemas
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_XMLReader
 * Method:    n_parseMetadata
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_vmf_XMLReader_n_1parseMetadata
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_XMLReader
 * Method:    n_parseVideoSegments
 * Signature: (JLjava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_intel_vmf_XMLReader_n_1parseVideoSegments
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_XMLReader
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_XMLReader_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
