/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_Reference */

#ifndef _Included_com_intel_vmf_Reference
#define _Included_com_intel_vmf_Reference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vmf_Reference
 * Method:    n_Reference
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Reference_n_1Reference__
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_vmf_Reference
 * Method:    n_Reference
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Reference_n_1Reference__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_Reference
 * Method:    n_ReferenceWeak
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Reference_n_1ReferenceWeak
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_Reference
 * Method:    n_getMetadata
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Reference_n_1getMetadata
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Reference
 * Method:    n_setMetadata
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Reference_n_1setMetadata
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_Reference
 * Method:    n_getReferenceDescription
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Reference_n_1getReferenceDescription
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Reference
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Reference_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
