/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_FieldDesc */

#ifndef _Included_com_intel_vmf_FieldDesc
#define _Included_com_intel_vmf_FieldDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_vmf_FieldDesc
 * Method:    n_FieldDesc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_FieldDesc_n_1FieldDesc__
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_vmf_FieldDesc
 * Method:    n_FieldDesc
 * Signature: (Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_FieldDesc_n_1FieldDesc__Ljava_lang_String_2IZ
  (JNIEnv *, jclass, jstring, jint, jboolean);

/*
 * Class:     com_intel_vmf_FieldDesc
 * Method:    n_equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_FieldDesc_n_1equals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_FieldDesc
 * Method:    n_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_FieldDesc_n_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_FieldDesc
 * Method:    n_getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_vmf_FieldDesc_n_1getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_FieldDesc
 * Method:    n_isOptional
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_FieldDesc_n_1isOptional
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_FieldDesc
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_FieldDesc_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
