/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_vmf_Metadata */

#ifndef _Included_com_intel_vmf_Metadata
#define _Included_com_intel_vmf_Metadata
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_vmf_Metadata_UNDEFINED_DURATION
#define com_intel_vmf_Metadata_UNDEFINED_DURATION 0i64
#undef com_intel_vmf_Metadata_NUMOFFRAMES_DEFAULT
#define com_intel_vmf_Metadata_NUMOFFRAMES_DEFAULT 1i64
/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_Metadata
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1Metadata
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_MetadataCopy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1MetadataCopy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getFrameIndex
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getFrameIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getNumOfFrames
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getNumOfFrames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_setFrameIndex
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1setFrameIndex
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_setTimestamp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1setTimestamp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_Metadata_n_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getSchemaName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_vmf_Metadata_n_1getSchemaName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getDesc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getDesc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getFieldNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_vmf_Metadata_n_1getFieldNames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getFieldValue
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getFieldValue
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_hasField
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_Metadata_n_1hasField
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_Metadata_n_1equals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_lessThan
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_Metadata_n_1lessThan
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getFirstReference
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getFirstReference
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getReferencesByMetadata
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getReferencesByMetadata
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getReferencesByName
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_vmf_Metadata_n_1getReferencesByName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_getAllReferences
 * Signature: (J)[Lcom/intel/vmf/Reference;
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_vmf_Metadata_n_1getAllReferences
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_isReferenceById
 * Signature: (JJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_Metadata_n_1isReferenceById
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_isReferenceByMd
 * Signature: (JJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_Metadata_n_1isReferenceByMd
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_addReference
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1addReference
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_removeReferenceById
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1removeReferenceById
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_removeReferenceByMd
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1removeReferenceByMd
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_setFieldValue
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1setFieldValue
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_addValue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1addValue
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_validate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1validate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_vmf_Metadata_n_1isValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_vmf_Metadata
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_vmf_Metadata_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
