/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FieldDesc */

#ifndef _Included_FieldDesc
#define _Included_FieldDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FieldDesc
 * Method:    n_FieldDesc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_FieldDesc_n_1FieldDesc__
  (JNIEnv *, jobject);

/*
 * Class:     FieldDesc
 * Method:    n_FieldDesc
 * Signature: (Ljava/lang/String;JZ)J
 */
JNIEXPORT jlong JNICALL Java_FieldDesc_n_1FieldDesc__Ljava_lang_String_2JZ
  (JNIEnv *, jobject, jstring, jlong, jboolean);

/*
 * Class:     FieldDesc
 * Method:    n_equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_FieldDesc_n_1equals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     FieldDesc
 * Method:    n_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FieldDesc_n_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     FieldDesc
 * Method:    n_getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_FieldDesc_n_1getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     FieldDesc
 * Method:    n_isOptional
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_FieldDesc_n_1isOptional
  (JNIEnv *, jclass, jlong);

/*
 * Class:     FieldDesc
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_FieldDesc_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
