/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FieldDesc */

#ifndef _Included_FieldDesc
#define _Included_FieldDesc
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
