/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSONReader */

#ifndef _Included_JSONReader
#define _Included_JSONReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSONReader
 * Method:    n_JSONReader
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JSONReader_n_1JSONReader
  (JNIEnv *, jobject);

/*
 * Class:     JSONReader
 * Method:    n_parseAll
 * Signature: (JLjava/lang/String;JLjava/lang/String;Ljava/lang/String;[LVideoSegment;[LMetadataSchema;[LMetadataInternal;)Z
 */
JNIEXPORT jboolean JNICALL Java_JSONReader_n_1parseAll
  (JNIEnv *, jclass, jlong, jstring, jlong, jstring, jstring, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     JSONReader
 * Method:    n_parseSchemas
 * Signature: (JLjava/lang/String;[LMetadataSchema;)Z
 */
JNIEXPORT jboolean JNICALL Java_JSONReader_n_1parseSchemas
  (JNIEnv *, jclass, jlong, jstring, jobjectArray);

/*
 * Class:     JSONReader
 * Method:    n_parseMetadata
 * Signature: (JLjava/lang/String;[LMetadataSchema;[LMetadataInternal;)Z
 */
JNIEXPORT jboolean JNICALL Java_JSONReader_n_1parseMetadata
  (JNIEnv *, jclass, jlong, jstring, jobjectArray, jobjectArray);

/*
 * Class:     JSONReader
 * Method:    n_parseVideoSegments
 * Signature: (JLjava/lang/String;[LVideoSegment;)Z
 */
JNIEXPORT jboolean JNICALL Java_JSONReader_n_1parseVideoSegments
  (JNIEnv *, jclass, jlong, jstring, jobjectArray);

/*
 * Class:     JSONReader
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JSONReader_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
