/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MetadataDesc */

#ifndef _Included_MetadataDesc
#define _Included_MetadataDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MetadataDesc
 * Method:    n_MetadataDesc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_MetadataDesc_n_1MetadataDesc__
  (JNIEnv *, jobject);

/*
 * Class:     MetadataDesc
 * Method:    n_MetadataDesc
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_MetadataDesc_n_1MetadataDesc__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     MetadataDesc
 * Method:    n_getMetadataName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MetadataDesc_n_1getMetadataName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     MetadataDesc
 * Method:    n_getSchemaName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MetadataDesc_n_1getSchemaName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     MetadataDesc
 * Method:    n_getFields
 * Signature: (J)[LFieldDesc;
 */
JNIEXPORT jobjectArray JNICALL Java_MetadataDesc_n_1getFields
  (JNIEnv *, jclass, jlong);

/*
 * Class:     MetadataDesc
 * Method:    n_getAllReferenceDescs
 * Signature: (J)[LReferenceDesc;
 */
JNIEXPORT jobjectArray JNICALL Java_MetadataDesc_n_1getAllReferenceDescs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     MetadataDesc
 * Method:    n_declareCustomReference
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_MetadataDesc_n_1declareCustomReference
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     MetadataDesc
 * Method:    n_getReferenceDesc
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_MetadataDesc_n_1getReferenceDesc
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     MetadataDesc
 * Method:    n_getFieldDesc
 * Signature: (JLFieldDesc;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_MetadataDesc_n_1getFieldDesc
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     MetadataDesc
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_MetadataDesc_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
