/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReferenceDesc */

#ifndef _Included_ReferenceDesc
#define _Included_ReferenceDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ReferenceDesc
 * Method:    n_ReferenceDesc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ReferenceDesc_n_1ReferenceDesc__
  (JNIEnv *, jobject);

/*
 * Class:     ReferenceDesc
 * Method:    n_ReferenceDesc
 * Signature: (Ljava/lang/String;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_ReferenceDesc_n_1ReferenceDesc__Ljava_lang_String_2ZZ
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     ReferenceDesc
 * Method:    n_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ReferenceDesc_n_1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ReferenceDesc
 * Method:    n_isUnique
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ReferenceDesc_n_1isUnique
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ReferenceDesc
 * Method:    n_isCustom
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ReferenceDesc_n_1isCustom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ReferenceDesc
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ReferenceDesc_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
