/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Reference */

#ifndef _Included_Reference
#define _Included_Reference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Reference
 * Method:    n_Reference
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Reference_n_1Reference__
  (JNIEnv *, jobject);

/*
 * Class:     Reference
 * Method:    n_Reference
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_Reference_n_1Reference__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Reference
 * Method:    n_getMetadata
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Reference_n_1getMetadata
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Reference
 * Method:    n_setMetadata
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_Reference_n_1setMetadata
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Reference
 * Method:    n_getReferenceDescription
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Reference_n_1getReferenceDescription
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Reference
 * Method:    n_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Reference_n_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
