/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReferenceDesc */

#ifndef _Included_ReferenceDesc
#define _Included_ReferenceDesc
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
