/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vmfRawBuffer */

#ifndef _Included_vmfRawBuffer
#define _Included_vmfRawBuffer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
